### PR TITLE
No more madness

### PR DESCRIPTION
**Pull request by lucventurini**
I have reorganised the CPC2 in a semi-sane way in our own fork here on GitHub.

Advantages:
- we control the version of the code, so easier to get a local copy etc etc etc
- Now CPC2 can be installed and runs with a simple `python3 setup.py bdist_wheel && pip install`.

I have updated the Singularity recipes and the GH action to reflect this.

Moreover, I have added CPC2 as a submodule in Git, and removed the old `install_cpc2` script.

### CODE REVIEW

**Review by cschu — COMMENTED** [review]
I'm not a particular fan of submodules as they're a b*tch to maintain. Hence, all of them were removed from the other production pipelines. Can't this be solved by just git cloning them into the container/environment?

Other question regarding running minos from a container: will this work with (slurm|other engines) ? Or is that container just for the CI?

**Comment by lucventurini** [comment]
> I'm not a particular fan of submodules as they're a b*tch to maintain. Hence, all of them were removed from the other production pipelines. Can't this be solved by just git cloning them into the container/environment?

Yes, not a problem with this. The important part is not having to resort to relatively brittle workarounds at the installation time. 

> Other question regarding running minos from a container: will this work with (slurm|other engines) ? Or is that container just for the CI?

Not sure, great point. I will test it on Monday and let you know!

**Comment by lucventurini** [comment]
> > Other question regarding running minos from a container: will this work with (slurm|other engines) ? Or is that container just for the CI?

@cschu 

I checked and you are right ... Minos cannot run from within the container while using sbatch.

**Comment by lucventurini** [comment]
@cschu @gemygk 

How would you like to proceed? I have removed CPC2 as a submodule, as you asked. I would like to merge to bring the changes to the `master` and make a new minor release (1.7.0) to signify the CPC2 change.

What do you think?

**Review by cschu — APPROVED** [review]
yup, looks good!

**Comment by lucventurini** [comment]
Excellent, thank you!

**Pull request merged**
